-- PEEPZ — schéma Supabase

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  signature text not null,
  signature_norm text not null unique,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_peepz_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  sig text;
begin
  sig := trim(coalesce(new.raw_user_meta_data->>'peepz_signature',''));
  if sig = '' then raise exception 'signature_required'; end if;
  insert into public.profiles(user_id,signature,signature_norm)
  values(new.id,sig,lower(sig));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_peepz on auth.users;
create trigger on_auth_user_created_peepz
after insert on auth.users
for each row execute function public.handle_new_peepz_user();

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_signature text not null,
  title text not null,
  content text not null,
  publication_date date not null default current_date,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(project_id,user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author text not null,
  content text not null,
  parent_id bigint references public.comments(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;

-- Profils : signatures publiques, modification seulement par le propriétaire
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select to anon,authenticated using (true);
drop policy if exists "profile owner update" on public.profiles;
create policy "profile owner update" on public.profiles for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

-- Projets : lecture publique, création/modification/suppression par le propriétaire
drop policy if exists "projects readable" on public.projects;
create policy "projects readable" on public.projects for select to authenticated using (published=true or user_id=auth.uid());
drop policy if exists "projects insert own" on public.projects;
create policy "projects insert own" on public.projects for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "projects update own" on public.projects;
create policy "projects update own" on public.projects for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists "projects delete own" on public.projects;
create policy "projects delete own" on public.projects for delete to authenticated using (user_id=auth.uid());

-- Likes : lecture publique, like/unlike par le compte connecté
drop policy if exists "likes readable" on public.likes;
create policy "likes readable" on public.likes for select to authenticated using (true);
drop policy if exists "likes insert own" on public.likes;
create policy "likes insert own" on public.likes for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "likes delete own" on public.likes;
create policy "likes delete own" on public.likes for delete to authenticated using (user_id=auth.uid());

-- Commentaires : lecture publique, publication/suppression de ses propres commentaires
drop policy if exists "comments readable" on public.comments;
create policy "comments readable" on public.comments for select to authenticated using (true);
drop policy if exists "comments insert own" on public.comments;
create policy "comments insert own" on public.comments for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "comments delete own" on public.comments;
create policy "comments delete own" on public.comments for delete to authenticated using (user_id=auth.uid());

-- Realtime optionnel
do $$ begin
  alter publication supabase_realtime add table public.likes;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.comments;
exception when duplicate_object then null; end $$;
